collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 1
  brandStrength: 0.8510638
  lightness: 0
  brandColors:
    - '#E8E9ED'
    - '#7AAEDD'
    - '#605755'
    - '#0064A2'
    - '#080803'
  rhythmicContrast: 0.3680851
typography_spectrum: 0
layout_spectrum: 0.2361702
name: The Viewfinder
